# Generated by Django 4.1.5 on 2023-01-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0003_customuser_smart_lead_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="celery_task_id_create_user_zoho_smartlead_list",
            field=models.TextField(blank=True, default="", max_length=25000, null=True),
        ),
    ]
