# Generated by Django 4.1.5 on 2023-01-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="celery_task_id_list",
            new_name="celery_task_id_add_domain_list",
        ),
        migrations.AddField(
            model_name="customuser",
            name="celery_task_id_create_user_zoho_list",
            field=models.TextField(blank=True, default="", max_length=25000, null=True),
        ),
    ]
