# Generated by Django 4.1.5 on 2023-01-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_user",
            "0004_customuser_celery_task_id_create_user_zoho_smartlead_list",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="access_token",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
