# Generated by Django 4.1.5 on 2023-01-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0005_customuser_access_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="access_token",
            field=models.CharField(
                blank=True, default="default12334", max_length=250, null=True
            ),
        ),
    ]
