# Generated by Django 4.1.5 on 2023-01-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0007_customuser_access_allowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="client_id",
            field=models.CharField(default="test", max_length=250),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="client_secret",
            field=models.CharField(default="test2", max_length=250),
        ),
    ]
