# Generated by Django 4.1.5 on 2023-01-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0009_alter_customuser_client_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
