# Generated by Django 4.1.5 on 2023-01-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0010_alter_customuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="tempUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.CharField(blank=True, max_length=250, null=True)),
                ("password", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
    ]
